server:
  port: 8020
spring:
  application:   #定义服务名称  必须定义
    name: consumer-user #hello world
  
eureka:
  client:
    service-url:
      #链接注册中心集群
       defaultZone: http://localhost:7000/eureka
   # register-with-eureka: false    #不会将自己的信息注册到eureka中
  instance:
    instance-id: consumer-user-8020                #定义微服务的名称  多个服务的id必须不同
    prefer-ip-address: true                       #是否显示IP和端口
    
feign:
  hystrix:
    enabled: true            #启动熔断器机制 !!!!!!!!!!!!!
